version: '3.8'
services:
  comet_db:
    image: rheagroup/cdp4-database-community-edition:3.0.0-rc1
    container_name: comet-db
    shm_size: 2gb
    restart: always
    command: postgres -c max_locks_per_transaction=1024
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    hostname: comet-db
    networks:
      cdp4-comet:
        aliases:
          - comet-db
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - comet-db-data:/var/lib/postgresql/data
      - comet-db-logs:/logs

  comet_ws:
    image: rheagroup/comet-webservices-community-edition:8.0.0-rc23
    container_name: comet-ws
    shm_size: 512m
    restart: always
    environment:
       - Backtier__IsDbSeedEnabled=true
    hostname: comet-ws
    networks:
      cdp4-comet:
        aliases:
          - comet-ws
    depends_on:
      - comet_db
    ports:
      - "5000:5000"
    expose:
      - '5000'
    volumes:
      - comet-ws-logs:/app/logs
      - comet-ws-storage:/app/storage
      - comet-ws-uplaod:/app/upload
      - comet-ws-tempstorage:/app/tempstorage
  comet-web:
    image: index.docker.io/rheagroup/comet-web-community-edition:latest
    container_name: comet-web
    depends_on:
      - comet-ws
    ports:
      - "8080:80"

networks:
  cdp4-comet:

volumes:
  comet-db-data:
  comet-db-logs:
  comet-ws-logs:
  comet-ws-storage:
  comet-ws-tempstorage:
  comet-ws-uplaod: